/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bdxh_Blur */

#ifndef _Included_com_bdxh_Blur
#define _Included_com_bdxh_Blur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bdxh_Blur
 * Method:    blur
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_bdxh_Blur_blur
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
